[package]
name = "sinitc"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.9", features = ["derive"] }
glob = "0.3.1"
serde = { version = "1.0.204", features = ["derive"] }
serde_toml = "0.0.1"
sysinfo = "0.30.13"
toml = "0.8.15"
